-- NorAutoMatch Garage / Match DNA / Market Scout R1
-- Applied to project xiqfmaibhhtffrxibiov on 2026-09-16.
-- RLS is owner-scoped; dossiers are readable only for VINs the current user saved.

create table if not exists public.match_dna_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  vin text not null check (vin ~ '^[A-HJ-NPR-Z0-9]{17}$'),
  action text not null check (action in ('pass','keep','mix','garage_save','garage_remove','battle')),
  surface text not null default 'unknown',
  year integer,
  make text,
  model text,
  trim text,
  condition text,
  body_type text,
  drivetrain text,
  price numeric,
  mileage integer,
  created_at timestamptz not null default now()
);
create index if not exists match_dna_events_user_created_idx on public.match_dna_events(user_id, created_at desc);
create index if not exists match_dna_events_user_vin_idx on public.match_dna_events(user_id, vin);
alter table public.match_dna_events enable row level security;
create policy match_dna_events_select_own on public.match_dna_events for select to authenticated using ((select auth.uid()) = user_id);
create policy match_dna_events_insert_own on public.match_dna_events for insert to authenticated with check ((select auth.uid()) = user_id);
create policy match_dna_events_delete_own on public.match_dna_events for delete to authenticated using ((select auth.uid()) = user_id);
revoke all on table public.match_dna_events from anon;
grant select, insert, delete on table public.match_dna_events to authenticated;
grant usage, select on sequence public.match_dna_events_id_seq to authenticated;

create table if not exists public.market_scout_jobs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  vin text not null check (vin ~ '^[A-HJ-NPR-Z0-9]{17}$'),
  status text not null default 'queued' check (status in ('queued','running','complete','failed')),
  requested_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_error text,
  unique (user_id, vin)
);
alter table public.market_scout_jobs enable row level security;
create policy market_scout_jobs_select_own on public.market_scout_jobs for select to authenticated using ((select auth.uid()) = user_id);
create policy market_scout_jobs_insert_own on public.market_scout_jobs for insert to authenticated with check ((select auth.uid()) = user_id);
revoke all on table public.market_scout_jobs from anon;
grant select, insert on table public.market_scout_jobs to authenticated;
grant usage, select on sequence public.market_scout_jobs_id_seq to authenticated;

create table if not exists public.vehicle_scout_dossiers (
  vin text primary key check (vin ~ '^[A-HJ-NPR-Z0-9]{17}$'),
  status text not null default 'pending' check (status in ('pending','researched','needs_refresh','failed')),
  research_version text not null default 'market-scout-r1',
  summary text,
  pros jsonb not null default '[]'::jsonb,
  cons jsonb not null default '[]'::jsonb,
  watch_items jsonb not null default '[]'::jsonb,
  sources jsonb not null default '[]'::jsonb,
  researched_at timestamptz,
  updated_at timestamptz not null default now()
);
alter table public.vehicle_scout_dossiers enable row level security;
create policy vehicle_scout_dossiers_saved_vehicle_select on public.vehicle_scout_dossiers for select to authenticated using (
  exists (
    select 1 from public.saved_vehicles sv
    where sv.user_id = (select auth.uid()) and sv.vin = vehicle_scout_dossiers.vin
  )
);
revoke all on table public.vehicle_scout_dossiers from anon, authenticated;
grant select on table public.vehicle_scout_dossiers to authenticated;
