import type { Metadata } from "next";

export const metadata: Metadata = { title: "Privacy & Contact Consent", description: "How NorAuto Match handles website lead information and communication consent." };

export default function PrivacyPage() {
  return <section className="py-20 sm:py-28"><div className="shell"><article className="mx-auto max-w-3xl"><p className="eyebrow">Plain-English policy</p><h1 className="mt-4 text-5xl font-black tracking-[-.04em] text-white">Privacy & contact consent</h1><div className="mt-10 space-y-8 text-sm leading-7 text-slate-400"><Policy title="What we collect">When you submit a request, we collect the contact, budget, vehicle, payment-method, and trade-in information you choose to provide, plus basic request metadata needed to prevent abuse.</Policy><Policy title="How we use it">We use that information only to respond to your vehicle request, source relevant options, coordinate with the licensed selling dealership, and improve the matching process.</Policy><Policy title="Calls and texts">By checking the consent box, you agree to receive calls, emails, or text messages about your request. Consent is not a condition of purchase. Message and data rates may apply. Reply STOP to opt out of text messages.</Policy><Policy title="Who receives it">A standard inventory inquiry routes to the Standard Retail pipeline. A sourcing or no-match request routes to the Auto Brokerage pipeline. Information may be shared with the licensed dealership only as needed to quote, sell, finance, register, or deliver a vehicle.</Policy><Policy title="What we do not do">We do not sell your personal information to data brokers. Do not submit Social Security numbers, bank details, driver-license images, or credit applications through this website.</Policy><Policy title="Contact">Questions or deletion requests: call or text (405) 861-0061.</Policy></div></article></div></section>;
}

function Policy({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border-t border-white/10 pt-6"><h2 className="text-xl font-black text-white">{title}</h2><p className="mt-2">{children}</p></section>; }
